"""empty message

Revision ID: 357da3cbd8
Revises: 97eb2c0fcc
Create Date: 2015-08-23 01:43:04.367058

"""

# revision identifiers, used by Alembic.
revision = '357da3cbd8'
down_revision = '97eb2c0fcc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
